let book=null,index=0,loading=false,saveTimer=null,searchTimer=null;
async function library(){const books=await api('/books?q='+encodeURIComponent($('#library-search').value));$('#book-count').textContent=`/ ${books.length} 本`;$('#books').innerHTML=books.length?books.map((b,i)=>{const percent=Math.round((b.chapter+b.ratio)/b.chapter_count*100);return `<article class="book-card"><div class="book-cover" style="filter:hue-rotate(${i%5*23}deg)"><span class="edition">YOUR PRIVATE LIBRARY</span><div class="title">${esc(b.title)}</div><span class="small">${b.chapter_count} CHAPTERS</span></div><div class="book-meta"><h3>${esc(b.title)}</h3><div class="small muted">${(b.characters/10000).toFixed(1)} 万字 · ${esc(b.encoding)}</div><div class="bar"><span style="width:${percent}%"></span></div><div class="small muted" style="margin-top:6px">已读 ${percent}%</div><button class="btn secondary open-book" data-id="${b.id}">${percent?'继续阅读':'开始阅读'} →</button></div></article>`;}).join(''):empty('给书架添上第一本书','导入一份TXT，章节、书签和进度会在这里安静地保存。');$$('.open-book').forEach(b=>b.onclick=guard(()=>openBook(b.dataset.id)));}
$('#file').onchange=guard(async()=>{const file=$('#file').files[0];if(!file)return;const form=new FormData();form.append('file',file);try{const b=await api('/books',{method:'POST',body:form});toast(b.duplicate?'这本书已经在书架中':'已导入，章节已准备好');await library();}finally{$('#file').value='';}});
$('#library-search').oninput=()=>{clearTimeout(searchTimer);searchTimer=setTimeout(()=>guard(library)(),200);};
function ratio(){const maximum=document.documentElement.scrollHeight-innerHeight;return maximum>0?Math.max(0,Math.min(1,scrollY/maximum)):0;}
async function save(){if(!book||loading)return;await post('/books/'+book.id+'/progress',{chapter:index,ratio:ratio()});$('#save-state').textContent='进度已保存到本机';}
async function marks(){const data=await api('/books/'+book.id+'/bookmarks');$('#marks').innerHTML=data.length?data.map(m=>`<div class="mark-row"><button class="mark-link" data-chapter="${m.chapter}" data-ratio="${m.ratio}">${esc(m.note||m.title)}</button><button class="delete-mark" data-id="${m.id}" aria-label="删除书签">×</button></div>`).join(''):'<p class="small muted">还没有书签</p>';$$('.mark-link').forEach(b=>b.onclick=guard(()=>openChapter(Number(b.dataset.chapter),Number(b.dataset.ratio))));$$('.delete-mark').forEach(b=>b.onclick=guard(async()=>{await api('/books/'+book.id+'/bookmarks/'+b.dataset.id,{method:'DELETE'});await marks();}));}
async function openChapter(next,position=0){if(next<0||next>=book.chapters.length)return;clearTimeout(saveTimer);await save();loading=true;try{const chapter=await api('/books/'+book.id+'/chapters/'+next);index=next;$('#chapter-number').textContent=`第 ${index+1} / ${book.chapters.length} 节`;$('#chapter-title').textContent=chapter.title;$('#body-text').textContent=chapter.text;$('#prev').disabled=index===0;$('#next').disabled=index===book.chapters.length-1;$$('.chapter-link').forEach(b=>b.classList.toggle('active',Number(b.dataset.index)===index));$('#reader .reader-toc').classList.remove('open');await post('/books/'+book.id+'/progress',{chapter:index,ratio:position});requestAnimationFrame(()=>{window.scrollTo(0,(document.documentElement.scrollHeight-innerHeight)*position);setTimeout(()=>loading=false,150);});}catch(e){loading=false;throw e;}}
async function openBook(id){book=await api('/books/'+id);loading=true;$('#library').classList.add('hidden');$('#reader').classList.remove('hidden');$('#book-title').textContent=book.title;$('#chapters').innerHTML=book.chapters.map(c=>`<button class="chapter-link" data-index="${c.idx}">${esc(c.title)}</button>`).join('');$$('.chapter-link').forEach(b=>b.onclick=guard(()=>openChapter(Number(b.dataset.index))));await openChapter(book.chapter,book.ratio);await marks();}
$('#back').onclick=guard(async()=>{clearTimeout(saveTimer);await save();book=null;$('#reader').classList.add('hidden');$('#library').classList.remove('hidden');document.body.removeAttribute('data-theme');await library();window.scrollTo(0,0);});
$('#prev').onclick=guard(()=>openChapter(index-1));$('#next').onclick=guard(()=>openChapter(index+1));$('#toc-toggle').onclick=()=>$('.reader-toc').classList.toggle('open');
$('#bookmark').onclick=guard(async()=>{await post('/books/'+book.id+'/bookmarks',{chapter:index,ratio:ratio(),note:''});await marks();toast('书签已保存');});
$('#text-search-form').onsubmit=guard(async e=>{e.preventDefault();const results=await api('/books/'+book.id+'/search?q='+encodeURIComponent($('#text-search').value));$('#search-results').innerHTML=results.length?results.map(r=>`<button class="result-link" data-chapter="${r.chapter}" data-ratio="${r.ratio}"><strong>${esc(r.title)}</strong><br>${esc(r.excerpt)}</button>`).join(''):'<p class="small muted">没有找到相关正文</p>';$$('.result-link').forEach(b=>b.onclick=guard(()=>openChapter(Number(b.dataset.chapter),Number(b.dataset.ratio))));});
function settings(){document.body.dataset.theme=$('#theme').value;$('#body-text').style.fontSize=$('#font').value+'px';try{localStorage.setItem('leafread-settings',JSON.stringify({theme:$('#theme').value,font:$('#font').value}));}catch{}}
$('#theme').onchange=settings;$('#font').onchange=settings;
window.addEventListener('scroll',()=>{if(!book||loading)return;clearTimeout(saveTimer);saveTimer=setTimeout(()=>guard(save)(),500);},{passive:true});
window.addEventListener('pagehide',()=>{if(book&&!loading)navigator.sendBeacon('/api/books/'+book.id+'/progress',new Blob([JSON.stringify({chapter:index,ratio:ratio()})],{type:'application/json'}));});
try{const prefs=JSON.parse(localStorage.getItem('leafread-settings')||'{}');if(['light','warm','dark'].includes(prefs.theme))$('#theme').value=prefs.theme;if(['18','20','24','28'].includes(prefs.font))$('#font').value=prefs.font;}catch{}
const originalOpen=openBook;openBook=async id=>{settings();await originalOpen(id);};
guard(library)();
