const libraryTools=document.createElement('div');libraryTools.className='row';libraryTools.innerHTML='<a class="btn secondary" href="/api/library/backup">备份书库</a><button class="btn secondary" id="trash-open">回收站</button>';$('#books').before(libraryTools);
const notesDialog=document.createElement('dialog');notesDialog.innerHTML='<h2 id="notes-title">阅读笔记</h2><div id="notes-content"></div><button class="btn secondary" id="notes-close">关闭</button>';document.body.append(notesDialog);$('#notes-close').onclick=()=>notesDialog.close();
const readerTools=document.createElement('div');readerTools.className='row';readerTools.style.margin='20px 0';readerTools.innerHTML='<button class="btn secondary" id="annotate">选段批注</button><button class="btn secondary" id="notes-open">阅读笔记</button><a class="btn secondary" id="export-book">导出 TXT</a><a class="btn secondary" id="export-notes">导出笔记</a><button class="btn secondary" id="delete-book">移到回收站</button>';$('.chapter-nav').before(readerTools);
const oldOpenBook=openBook;openBook=async id=>{await oldOpenBook(id);$('#export-book').href='/api/library/books/'+id+'/export';$('#export-notes').href='/api/library/books/'+id+'/notes-export';};
$('#annotate').onclick=guard(async()=>{const selected=getSelection();const quote=selected?.toString().trim();if(!quote||!$('#body-text').contains(selected.anchorNode)||!$('#body-text').contains(selected.focusNode))return toast('先在正文中选择一段文字');const note=prompt('为这段文字写一点想法','');if(note===null)return;await post('/library/books/'+book.id+'/annotations',{chapter:index,quote,note});toast('批注已保存');});
$('#notes-open').onclick=guard(async()=>{const data=await api('/library/books/'+book.id+'/annotations');$('#notes-title').textContent='阅读笔记';$('#notes-content').innerHTML=data.map(n=>`<article style="margin:20px 0"><blockquote class="answer">${esc(n.quote)}</blockquote><p class="answer">${esc(n.note)}</p><button class="btn secondary edit-note" data-id="${n.id}">编辑</button><button class="btn secondary remove-note" data-id="${n.id}">删除</button></article>`).join('')||empty('还没有批注','选中正文，然后点击“选段批注”');notesDialog.showModal();$$('.edit-note').forEach(b=>b.onclick=guard(async()=>{const note=prompt('修改批注',data.find(n=>n.id===b.dataset.id).note);if(note!==null){await api('/library/books/'+book.id+'/annotations/'+b.dataset.id,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({note})});notesDialog.close();toast('已保存');}}));$$('.remove-note').forEach(b=>b.onclick=guard(async()=>{await api('/library/books/'+book.id+'/annotations/'+b.dataset.id,{method:'DELETE'});notesDialog.close();toast('笔记已删除');}));});
$('#delete-book').onclick=guard(async()=>{if(!confirm('移入回收站？可恢复。'))return;const ident=book.id;await $('#back').onclick();await api('/library/books/'+ident,{method:'DELETE'});await library();});
$('#trash-open').onclick=guard(async()=>{const data=await api('/library/trash');$('#notes-title').textContent='回收站';$('#notes-content').innerHTML=data.map(b=>`<p>${esc(b.title)} <button class="btn secondary restore-book" data-id="${b.id}">恢复</button></p>`).join('')||empty('回收站为空','');notesDialog.showModal();$$('.restore-book').forEach(b=>b.onclick=guard(async()=>{await post('/library/books/'+b.dataset.id+'/restore',{});notesDialog.close();await library();}));});
window.addEventListener('keydown',e=>{if(!book||/INPUT|TEXTAREA|SELECT/.test(e.target.tagName)||document.querySelector('dialog[open]'))return;if(e.key==='ArrowRight'){e.preventDefault();guard(()=>openChapter(index+1))();}if(e.key==='ArrowLeft'){e.preventDefault();guard(()=>openChapter(index-1))();}if(e.key==='Escape')guard(()=>$('#back').onclick())();});
if('serviceWorker' in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{});

const restoreLabel=document.createElement('label');restoreLabel.className='btn secondary file-label';restoreLabel.innerHTML='恢复书库备份<input type="file" class="hidden" id="restore-library" accept=".json">';libraryTools.append(restoreLabel);$('#restore-library').onchange=guard(async()=>{const form=new FormData();form.append('file',$('#restore-library').files[0]);const result=await api('/library/restore-backup',{method:'POST',body:form});toast(`已恢复${result.imported}本书`);await library();});


const baseMarks=marks;marks=async()=>{await baseMarks();$$('.delete-mark').forEach(remove=>{const edit=document.createElement('button');edit.className='btn secondary';edit.textContent='编辑';remove.before(edit);edit.onclick=guard(async()=>{const note=prompt('修改书签备注');if(note!==null){await api('/library/books/'+book.id+'/bookmarks/'+remove.dataset.id,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({note})});await marks();}});});};
const textSearchSubmit=$('#text-search-form').onsubmit;$('#text-search-form').onsubmit=async e=>{await textSearchSubmit(e);const query=$('#text-search').value;if(!query)return;$$('#search-results .result-link').forEach(button=>{const lines=button.childNodes;for(const node of [...lines])if(node.nodeType===Node.TEXT_NODE){const text=node.textContent;let at=0,start;const fragment=document.createDocumentFragment();while((start=text.toLowerCase().indexOf(query.toLowerCase(),at))>=0){fragment.append(document.createTextNode(text.slice(at,start)));const mark=document.createElement('mark');mark.textContent=text.slice(start,start+query.length);fragment.append(mark);at=start+query.length;}fragment.append(document.createTextNode(text.slice(at)));node.replaceWith(fragment);}});};

