// Offline copies are scoped to the active local account and only cache library read APIs.
let offlineUser='local';
function offlineDB(){return new Promise((resolve,reject)=>{const req=indexedDB.open('leafread-offline-v1',1);req.onupgradeneeded=()=>req.result.createObjectStore('responses');req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});}
async function offlineRead(key){const db=await offlineDB();return new Promise((resolve,reject)=>{const tx=db.transaction('responses','readonly');const req=tx.objectStore('responses').get(key);req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);tx.oncomplete=()=>db.close();});}
async function offlineWrite(key,value){const db=await offlineDB();return new Promise((resolve,reject)=>{const tx=db.transaction('responses','readwrite');tx.objectStore('responses').put(value,key);tx.oncomplete=()=>{db.close();resolve();};tx.onerror=()=>reject(tx.error);});}
const liveApi=api;api=async(path,options={})=>{const read=!options.method||options.method==='GET';const cacheable=read&&(/^\/books(?:\/|\?|$)/.test(path)||/^\/library\/books\/[^/]+\/sync$/.test(path));try{const result=await liveApi(path,options);if(path==='/auth/me'){offlineUser=result.id;await offlineWrite('identity',result);}if(path==='/auth/logout'){localStorage.removeItem(pendingKey());const db=await offlineDB();await new Promise(resolve=>{const tx=db.transaction('responses','readwrite');tx.objectStore('responses').clear();tx.oncomplete=resolve;});db.close();}if(cacheable)await offlineWrite(offlineUser+':'+path,result);return result;}catch(error){if(!navigator.onLine||error instanceof TypeError){if(path==='/auth/me'){const saved=await offlineRead('identity');if(saved){offlineUser=saved.id;return saved;}}if(cacheable){const saved=await offlineRead(offlineUser+':'+path);if(saved)return saved;}}throw error;}};
const versions=new Map();let positionChain=Promise.resolve();
function pendingKey(){return 'leafread-pending:'+offlineUser;}
function pendingPositions(){try{return JSON.parse(localStorage.getItem(pendingKey())||'{}');}catch{return {};}}
function queuePosition(id,position){const queue=pendingPositions();queue[id]={...position,version:queue[id]?.version??versions.get(id)??0};localStorage.setItem(pendingKey(),JSON.stringify(queue));}
async function writePosition(id,position){const path='/library/books/'+id+'/sync';if(!versions.has(id)){const state=await api(path);versions.set(id,state.version);}const result=await post(path,{...position,version:versions.get(id)});versions.set(id,result.version);await offlineWrite(offlineUser+':'+path,{...position,version:result.version});}
function persistPosition(id,position){positionChain=positionChain.catch(()=>{}).then(async()=>{try{if(!navigator.onLine)throw new TypeError('offline');const pending=pendingPositions()[id];if(pending){const remote=await api('/library/books/'+id+'/sync');if(remote.chapter!==pending.chapter||Math.abs(remote.ratio-pending.ratio)>.001){versions.set(id,pending.version);await writePosition(id,pending);}else versions.set(id,remote.version);const queue=pendingPositions();delete queue[id];localStorage.setItem(pendingKey(),JSON.stringify(queue));}await writePosition(id,position);$('#save-state').textContent='进度已同步';}catch(error){queuePosition(id,position);$('#save-state').textContent=error.status===409?'进度冲突：点击“处理同步冲突”':'进度保存在本机，联网后同步';if(error.status&&error.status!==409)throw error;}});return positionChain;}
async function replayPositions(){await api('/auth/me');for(const [id,position] of Object.entries(pendingPositions())){versions.set(id,position.version);try{const remote=await api('/library/books/'+id+'/sync');if(remote.chapter!==position.chapter||Math.abs(remote.ratio-position.ratio)>.001)await writePosition(id,position);else versions.set(id,remote.version);const queue=pendingPositions();delete queue[id];localStorage.setItem(pendingKey(),JSON.stringify(queue));}catch(error){if(error.status===409)toast('阅读进度冲突，打开书籍后处理同步冲突',true);}}}
function scheduledReplay(){positionChain=positionChain.catch(()=>{}).then(replayPositions);return positionChain;}
window.addEventListener('online',()=>guard(scheduledReplay)());
const resolveSync=document.createElement('button');resolveSync.className='btn secondary';resolveSync.textContent='处理同步冲突';document.querySelector('.chapter-nav').before(resolveSync);resolveSync.onclick=guard(async()=>{if(!book)return;const id=book.id,local=pendingPositions()[id];const remote=await api('/library/books/'+id+'/sync');versions.set(id,remote.version);if(local&&confirm(`服务器在第${remote.chapter+1}节，本机在第${local.chapter+1}节。使用本机进度覆盖服务器？取消则使用服务器进度。`))await writePosition(id,local);const queue=pendingPositions();delete queue[id];localStorage.setItem(pendingKey(),JSON.stringify(queue));await openBook(id);toast('同步冲突已处理');});
async function downloadOffline(){if(!book)return;toast('正在保存整本书的离线副本…');await api('/auth/me');await api('/books/'+book.id);const state=await api('/library/books/'+book.id+'/sync');versions.set(book.id,state.version);for(const c of book.chapters)await api('/books/'+book.id+'/chapters/'+c.idx);await api('/books/'+book.id+'/bookmarks');toast('整本书已可离线阅读');}
const offlineButton=document.createElement('button');offlineButton.className='btn secondary';offlineButton.textContent='保存整本离线副本';document.querySelector('.chapter-nav').before(offlineButton);offlineButton.onclick=guard(downloadOffline);
window.addEventListener('DOMContentLoaded',()=>guard(async()=>{await refreshAccount();await library();if(navigator.onLine)await scheduledReplay();})(),{once:true});
